MENDELEY_OAUTH_CONSUMER_KEY ||= ENV['MENDELEY_OAUTH_CONSUMER_KEY'] || raise("Set ENV['MENDELEY_OAUTH_CONSUMER_KEY']") 
MENDELEY_OAUTH_CONSUMER_SECRET ||= ENV['MENDELEY_OAUTH_CONSUMER_SECRET'] || raise("Set ENV['MENDELEY_OAUTH_CONSUMER_SECRET']") 
