ZOTERO_OAUTH_CONSUMER_KEY ||= ENV['ZOTERO_OAUTH_CONSUMER_KEY'] || raise("Set ENV['ZOTERO_OAUTH_CONSUMER_KEY']") 
ZOTERO_OAUTH_CONSUMER_SECRET ||= ENV['ZOTERO_OAUTH_CONSUMER_SECRET'] || raise("Set ENV['ZOTERO_OAUTH_CONSUMER_SECRET']") 
